apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config-b-init
  namespace: apps
data:
  agent.hcl: |
    exit_after_auth = false

    auto_auth {
      method "approle" {
        mount_path = "auth/approle"
        config = {
          role_id_file_path    = "/vault/creds/role_id"
          # Agent will read the secret_id produced by the init container
          secret_id_file_path  = "/vault/creds/secret_id"
          # Once validated and stable, set to true to remove the secret file after reading
          remove_secret_id_file_after_reading = true
        }
      }
      sink "file" {
        config = { path = "/home/vault/.vault-token" }
      }
    }

    template {
      source      = "/vault/templates/db.env.tmpl"
      destination = "/vault/secrets/db.env"
      command     = "sh -c 'chmod 0640 /vault/secrets/db.env'"
    }

  db.env.tmpl: |
    {{- $role := env "VAULT_DB_ROLE" -}}
    {{- with secret (printf "database/creds/%s" $role) -}}
    DB_USER={{ .Data.username }}
    DB_PASSWORD={{ .Data.password }}
    {{- if .LeaseID }}
    DB_LEASE_ID={{ .LeaseID }}
    {{- end }}
    {{- if .LeaseDuration }}
    DB_LEASE_TTL={{ .LeaseDuration }}
    {{- end }}
    {{- end }}
