apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-b
  namespace: apps
type: Opaque
stringData:
  role_id: "9ad885d3-3723-5bdc-707c-4ceb4e092814"
  secret_id: "5d9fb1d0-5ff4-cd88-ce6e-b326a4bcc56a"   # for prod, prefer a wrapped SecretID
