apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-b
  namespace: apps
type: Opaque
stringData:
  role_id: "9ad885d3-3723-5bdc-707c-4ceb4e092814"
  secret_id: "10274b0d-bf9d-584f-4247-d1757eb3ae53"
  WRAPPED_TOKEN: "hvs.CAESIObvqkO5c9GxmA7etNEqCHXHUVRY491fXoA0BUeDeoG6Gh4KHGh2cy5VcXJvRUZGNTZ6M0ZDdU1XRFVsanMyVVA"   # for prod, prefer a wrapped SecretID
