apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-b
  namespace: apps
type: Opaque
stringData:
  role_id: "9ad885d3-3723-5bdc-707c-4ceb4e092814"
  WRAPPED_TOKEN: "hvs.CAESIGir4yyquQG-agn6lqM5wpkWsJ0aM_XDtvRGQW7fXmYfGh4KHGh2cy5IcDBFZnVHQmQ2RlNHMTMxamk5MTNVcGM"
  # secret_id: "10274b0d-bf9d-584f-4247-d1757eb3ae53"