# svc-endpoints-pg.yaml
apiVersion: v1
kind: Service
metadata:
  name: pg-db
  namespace: apps
spec:
  clusterIP: None
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  selector: {}   # no selector; we supply Endpoints
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg-db
  namespace: apps
subsets:
  - addresses:
      - ip: 10.20.4.4   # ← your Postgres VM IP(s) in Sub4
      - ip: 10.20.4.5
    ports:
      - name: pg
        port: 5432
